#!/usr/bin/env python3
"""Send a generated U-Boot mw.l script, waiting for the prompt per command.

Close Minicom before using this program: it opens the serial device itself.
"""

import argparse
import os
import re
import select
import sys
import termios
import time
from pathlib import Path


MW_L_COMMAND = re.compile(
    r"^mw\.l\s+\S+\s+\S+\s+(0x[0-9a-fA-F]+|[0-9]+)$")
FILESIZE_COMMAND = re.compile(r"^setenv\s+filesize\s+(0x[0-9a-fA-F]+|[0-9]+)$")


def configure_serial(fd: int, baud: int) -> None:
    baud_flag = getattr(termios, f"B{baud}", None)
    if baud_flag is None:
        raise ValueError(f"unsupported baud rate: {baud}")
    attrs = termios.tcgetattr(fd)
    attrs[0] = 0
    attrs[1] = 0
    attrs[2] &= ~(termios.PARENB | termios.CSTOPB | termios.CSIZE)
    attrs[2] |= termios.CLOCAL | termios.CREAD | termios.CS8
    if hasattr(termios, "CRTSCTS"):
        attrs[2] &= ~termios.CRTSCTS
    attrs[3] = 0
    attrs[4] = baud_flag
    attrs[5] = baud_flag
    attrs[6][termios.VMIN] = 0
    attrs[6][termios.VTIME] = 1
    termios.tcsetattr(fd, termios.TCSANOW, attrs)


def write_all(fd: int, payload: bytes) -> None:
    while payload:
        _, writable, _ = select.select([], [fd], [], 5)
        if not writable:
            raise TimeoutError("serial port did not become writable")
        written = os.write(fd, payload)
        payload = payload[written:]


def wait_for_prompt(fd: int, prompt: bytes, timeout: float,
                    show_serial: bool = False) -> None:
    received = bytearray()
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        ready, _, _ = select.select([fd], [], [], max(0, deadline - time.monotonic()))
        if not ready:
            continue
        chunk = os.read(fd, 4096)
        if not chunk:
            continue
        if show_serial:
            sys.stdout.buffer.write(chunk)
            sys.stdout.buffer.flush()
        received.extend(chunk)
        if prompt in received:
            return
        # Retain enough history to match a prompt split across reads.
        if len(received) > len(prompt):
            del received[:-len(prompt)]
    raise TimeoutError(f"timed out waiting for {prompt.decode(errors='replace')!r}")


def command_bytes(command: str) -> int:
    """Return the number of bytes written by one mw.l command."""
    match = MW_L_COMMAND.match(command)
    return int(match.group(1), 0) * 4 if match else 0


def upload_size(commands: list[str]) -> int:
    """Read the unpadded payload size emitted by uboot-mw-upload.py."""
    for command in commands:
        match = FILESIZE_COMMAND.match(command)
        if match:
            return int(match.group(1), 0)
    return sum(command_bytes(command) for command in commands)


def format_duration(seconds: float) -> str:
    seconds = max(0, int(seconds))
    hours, seconds = divmod(seconds, 3600)
    minutes, seconds = divmod(seconds, 60)
    if hours:
        return f"{hours:d}:{minutes:02d}:{seconds:02d}"
    return f"{minutes:02d}:{seconds:02d}"


def show_progress(done: int, total: int, started: float, width: int) -> None:
    elapsed = max(time.monotonic() - started, 0.001)
    fraction = min(done / total, 1.0) if total else 1.0
    filled = int(fraction * width)
    rate = done / elapsed
    eta = (total - done) / rate if rate else 0
    bar = "#" * filled + "-" * (width - filled)
    print(
        f"\r[{bar}] {fraction:6.2%}  {done}/{total} B  "
        f"{rate / 1024:.1f} KiB/s  ETA {format_duration(eta)}",
        end="", file=sys.stderr, flush=True)


def main() -> None:
    parser = argparse.ArgumentParser(description="Reliably send U-Boot mw.l commands over serial")
    parser.add_argument("port", help="serial device, e.g. /dev/ttyUSB0")
    parser.add_argument("commands", type=Path, help="file generated by uboot-mw-upload.py")
    parser.add_argument("--baud", type=int, default=115200)
    parser.add_argument("--prompt", default="IPQ9574# ")
    parser.add_argument("--timeout", type=float, default=10.0,
                        help="seconds to wait for each U-Boot prompt")
    parser.add_argument("--no-progress", action="store_true",
                        help="disable the transfer progress display")
    parser.add_argument("--progress-width", type=int, default=30,
                        help="width of the progress bar in characters")
    parser.add_argument("--verbose", action="store_true",
                        help="also print echoed commands and U-Boot output")
    args = parser.parse_args()

    lines = [line.strip() for line in args.commands.read_text().splitlines()
             if line.strip() and not line.lstrip().startswith("#")]
    if not lines:
        parser.error("command file contains no commands")
    if args.progress_width < 1:
        parser.error("--progress-width must be positive")

    total = upload_size(lines)
    transferred = 0

    fd = os.open(args.port, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
    try:
        configure_serial(fd, args.baud)
        termios.tcflush(fd, termios.TCIFLUSH)
        # Obtain a fresh prompt before beginning the upload.
        write_all(fd, b"\r")
        wait_for_prompt(fd, args.prompt.encode(), args.timeout, args.verbose)
        started = time.monotonic()
        if not args.no_progress:
            show_progress(transferred, total, started, args.progress_width)
        for number, line in enumerate(lines, 1):
            command_size = command_bytes(line)
            if not args.no_progress and not command_size:
                print(file=sys.stderr)
            if not command_size:
                print(f"[{number}/{len(lines)}] {line}", file=sys.stderr)
            write_all(fd, line.encode() + b"\r")
            wait_for_prompt(fd, args.prompt.encode(), args.timeout, args.verbose)
            if command_size:
                transferred = min(transferred + command_size, total)
                if not args.no_progress:
                    show_progress(transferred, total, started, args.progress_width)
        if not args.no_progress:
            print(file=sys.stderr)
    finally:
        os.close(fd)


if __name__ == "__main__":
    main()
