name: Test Formalities

on:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Test Formalities
    uses: robimarko/actions-shared-workflows/.github/workflows/formal.yml@buildworker-bump
