name: Issue Labeller
on:
  issues:
    types: [ opened ]

jobs:
  label-component:
    name: Validate and Tag Bug Report
    permissions:
      issues: write
    uses: robimarko/actions-shared-workflows/.github/workflows/issue-labeller.yml@buildworker-bump
